version = "0.1.0"
author = "local"
description = "Standalone libp2p mix protocol example"
license = "MIT"
srcDir = "."

requires "nim >= 2.0.0"
requires "libp2p >= 1.15.3"
requires "chronicles >= 0.11.0"
requires "chronos >= 4.2.2"
requires "results >= 0.5.0"
